# Generated by Django 3.0.5 on 2020-04-23 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200423_0341'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermoney',
            name='u_dime',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vendingmachinemoney',
            name='m_dime',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
