# Generated by Django 3.0.5 on 2020-04-26 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200423_0345'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendingItemsNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200, unique=True)),
                ('item_price', models.PositiveIntegerField()),
                ('item_quantity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_purchase', models.DateTimeField()),
                ('item_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.VendingItemsNew')),
            ],
        ),
    ]
